### ISSUE TITLE
Code doesn't show fluids in matlplotlib graph

### ISSUE THREAD

**Issue by a43nigam** [AlexandreSajus/Python-2D-SPH#2]
Running it for the first time without changing anything shows an empty graph with no particles.

**Comment by AlexandreSajus** [comment]
Hi,

Weird, the code works fine on my end. What exactly do you see, do you see a blue rectangle on the left of the plot? Can you give me more details about where you are running the script from (IDE, OS?)? Chances are matplotlib.animate isnt natively supported on some IDEs (I tried running the script on Spyder and the plot doesnt animate.) Try running it in Pycharm or Pyzo with Anaconda.

Anyways I hope this helps, don’t hesitate to ask anything.

Best Regards,
Alexandre Sajus

**Comment by a43nigam** [comment]
Hello,

I attached an image of the plot. I don't see any sort of blue rectangle anywhere. I am running this on Windows 10 on Pycharm. I am also using Python 3.9.

![Capture](https://user-images.githubusercontent.com/68975730/101960165-6fccec00-3bcc-11eb-8a21-913f1719ab24.PNG)

**Comment by AlexandreSajus** [comment]
Extremely weird, can you run it on the latest distribution of Anaconda
Python, my best guess is a version problem with the modules. Can you add a
"print(visual)" between lines 184 and 185, it should return arrays with
varying floats. If it doesn't something is wrong with the simulation, if it
does then its a problem with matplotlib.animation.

**Comment by a43nigam** [comment]
It does print out the arrays. I tried reinstalling matplotlib, but that doesn't work either.

**Comment by AlexandreSajus** [comment]
Honestly I dont know, something is definitely wrong with matplotlib.animate. I don’t know how to help you sorry. But at least you have the simulation: visual stores the coordinates of every particle at each step, if you can find a way to plot them with something else than matplotlib then it’ll work.

**Comment by a43nigam** [comment]
I managed to solve the problem from [this stackoverflow answer](https://stackoverflow.com/a/55955602/14063966). It appears that running the animation in the tool window does not work, whereas disabling that feature and running the animation in its own window allows the animation to work.
